<a href="https://colab.research.google.com/github/prof-programmer/learn_data_sciense/blob/main/Pandas_23_yakuniy_vazifa_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. Pandas kutubxonasi.

### PANDAS. Yakuniy vazifa. **2-Qism**

## Dataset
#### Ushbu vazifada biz turli davlatlarning turli yillarda elektr tokini qanday manbaalardan olganini ko'rsatuvchi jadval bilan ishlaymiz.
Jadval ustunlari ko'mir, gaz, gidro va boshqa manbaalardan ko'rsatilgan yilda qancha __terravat/soat__ energiya olinganini ko'rsatadi.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/Electricity_Production_By_Source.csv")
df.columns = ['davlat','kod','yil','komir','gaz','gidro','yangilanuvchi','quyosh','neft','shamol','atom']
df.head()

,davlat,kod,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
0,Afghanistan,AFG,2000,0.0,0.155,0.312,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.0,0.094,0.498,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.0,0.132,0.555,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.0,0.309,0.630,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.0,0.329,0.565,0.0,0.0,0.0,0.0,0.0

### 1-VAZIFA. DF hajmini chiqaring

In [3]:
# JAVOBNI SHU YERGA YOZING
df.shape

(6241, 11)

### 2-VAZIFA. Jadvalda mavjud davlatlar ro'yxatini alohida chiqaring

In [4]:
# JAVOBNI SHU YERGA YOZING
df.davlat.unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa',
       'Angola', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Asia Pacific', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'CIS', 'Cambodia', 'Cameroon', 'Canada',
       'Cayman Islands', 'Central African Republic', 'Central America',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'EU-27', 'EU27+1',
       'Eastern Africa', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Europe',
       'Europe (other)', 'Falkland Islands', 'Faroe Islands', 'Fiji',
       'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece',
       'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Lithuania', 'Luxembourg', 'Macau', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Martinique',
       'Mauritania', 'Mauritius', 'Mexico', 'Middle Africa',
       'Middle East', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat',
       'Morocco', 'Mozambique', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'Netherlands Antilles', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North America', 'North Korea', 'North Macedonia', 'Norway',
       'Oman', 'Other Asia & Pacific', 'Other CIS', 'Other Caribbean',
       'Other Middle East', 'Other Northern Africa',
       'Other South America', 'Other Southern Africa', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia',
       'South & Central America', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Turkmenistan', 'Turks and Caicos Islands',
       'U.S. Pacific Islands', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Western Africa', 'Western Sahara',
       'World', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
#@title Kutilgan natija

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa',
       'Angola', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Asia Pacific', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'CIS', 'Cambodia', 'Cameroon', 'Canada',
       'Cayman Islands', 'Central African Republic', 'Central America',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'EU-27', 'EU27+1',
       'Eastern Africa', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Europe',
       'Europe (other)', 'Falkland Islands', 'Faroe Islands', 'Fiji',
       'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece',
       'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Lithuania', 'Luxembourg', 'Macau', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Martinique',
       'Mauritania', 'Mauritius', 'Mexico', 'Middle Africa',
       'Middle East', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat',
       'Morocco', 'Mozambique', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'Netherlands Antilles', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North America', 'North Korea', 'North Macedonia', 'Norway',
       'Oman', 'Other Asia & Pacific', 'Other CIS', 'Other Caribbean',
       'Other Middle East', 'Other Northern Africa',
       'Other South America', 'Other Southern Africa', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia',
       'South & Central America', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Turkmenistan', 'Turks and Caicos Islands',
       'U.S. Pacific Islands', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Western Africa', 'Western Sahara',
       'World', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

### 3-VAZIFA. DF dan faqat AQSh (`United States`) uchun ma'lumotlarni ajratib oling va yangi `dfus` nomli o'zgaruvchiga saqlang

In [5]:
# JAVOBNI SHU YERGA YOZING
dfus = df[df.kod == 'USA']
dfus.tail()

,davlat,kod,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
5918,United States,USA,2016,1239.148654,1391.114366,261.126026,78.586265,54.866492,37.959041,226.992562,805.693948
5919,United States,USA,2017,1205.835275,1308.883659,293.838608,78.688434,77.276459,34.486074,254.302662,804.949635
5920,United States,USA,2018,1145.962192,1482.189373,286.619450,77.868208,93.364598,38.198843,272.649789,807.084477
5921,United States,USA,2019,964.957000,1598.303000,282.613000,72.980000,106.894000,31.772000,294.906000,809.409262
5922,United States,USA,2020,773.805528,1629.236806,285.789644,72.984923,132.630484,28.947190,336.533331,789.918631

In [ ]:
#@title Kutilgan natija
dfus.head(6)

             davlat  kod   yil  ...        neft    shamol        atom
5887  United States  USA  1985  ...  107.744380  0.005820  403.884976
5888  United States  USA  1986  ...  146.865448  0.004231  435.829540
5889  United States  USA  1987  ...  127.411367  0.003577  479.231981
5890  United States  USA  1988  ...  160.107055  0.000880  554.708470
5891  United States  USA  1989  ...  176.729591  2.133377  557.215492
5892  United States  USA  1990  ...  135.978712  2.816768  607.222819

[6 rows x 11 columns]

### 4-VAZIFA. `dfus` jadvalining indeksini `yil` ustuni bilan o'zgartiring. DF dan `yil` ustunini tashlab yuboring.

In [6]:
# JAVOBNI SHU YERGA YOZING
dfus = dfus.set_index('yil')
dfus

,davlat,kod,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
yil,,,,,,,,,,
1985,United States,USA,1507.664651,313.920392,287.182362,36.392894,0.010737,107.744380,0.005820,403.884976
1986,United States,USA,1490.141346,267.213369,296.974969,38.701672,0.014174,146.865448,0.004231,435.829540
1987,United States,USA,1573.958375,293.140648,255.410195,42.665433,0.010603,127.411367,0.003577,479.231981
1988,United States,USA,1656.615886,271.828714,228.384649,42.394061,0.009186,160.107055,0.000880,554.708470
1989,United States,USA,1711.442534,379.170824,274.724178,48.854268,0.253132,176.729591,2.133377,557.215492
1990,United States,USA,1725.155171,400.822746,292.280914,57.459315,0.370795,135.978712,2.816768,607.222819
1991,United States,USA,1722.535851,410.272061,287.326014,60.551763,0.478253,128.765132,2.980759,644.805355
1992,United States,USA,1757.501372,434.488572,251.425678,64.815412,0.408844,107.692648,2.916690,651.343435
1993,United States,USA,1831.210785,446.157847,279.250946,66.924724,0.475162,121.277613,3.036189,642.411804
1994,United States,USA,1832.271952,494.858798,259.341321,66.354857,0.501873,113.872025,3.481928,674.147192
1995,United States,USA,1853.006902,533.395640,311.219815,63.265079,0.514472,80.165661,3.196215,708.844340
1996,United States,USA,1945.754200,489.307071,347.549480,64.825960,0.541341,87.538952,3.266736,710.240575
1997,United States,USA,1998.243409,515.482441,355.973121,65.820084,0.532696,99.521369,3.321247,661.730706
1998,United States,USA,2029.040774,571.244198,322.089274,65.617126,0.524659,138.494810,3.056259,709.160109
1999,United States,USA,2037.863243,598.275405,316.605182,66.477721,0.518342,126.947138,4.533331,766.583288
2000,United States,USA,1966.265000,614.993000,270.034000,74.819000,0.493000,116.015000,5.593000,753.893000
2001,United States,USA,1903.955943,648.168593,208.137599,63.488559,0.542755,136.786564,6.737332,768.826308
2002,United States,USA,1933.130354,702.468431,255.585905,68.200062,0.554831,108.094305,10.354279,780.064087
2003,United States,USA,1973.736750,665.507561,267.271263,67.765320,0.534001,133.450147,11.187467,763.732695
2004,United States,USA,1978.300549,725.352447,259.929098,68.348428,0.575155,135.377458,14.143741,788.528387
2005,United States,USA,2012.873046,774.424398,263.763467,68.968555,0.550294,135.046076,17.810549,781.986365
2006,United States,USA,1990.511135,830.617578,282.688574,69.428650,0.507706,77.140813,26.589137,787.218636
2007,United States,USA,2016.455584,910.043145,240.613622,70.175791,0.611793,77.970109,34.449927,806.424753
2008,United States,USA,1985.801247,894.687475,248.543323,69.873588,0.864315,58.046277,55.363100,806.208435
2009,United States,USA,1755.904253,931.610787,268.817749,69.501392,0.891179,50.864849,73.886132,798.854585
2010,United States,USA,1847.290279,999.010021,254.701937,71.308579,1.212182,49.916355,94.652246,806.968301
2011,United States,USA,1733.430005,1025.255129,312.934388,71.986898,1.817696,44.335845,120.176599,790.204367
2012,United States,USA,1514.042945,1237.791760,271.289723,73.184591,4.326675,36.976608,140.821715,769.331249
2013,United States,USA,1581.114716,1137.688497,263.884350,76.632701,9.035620,40.751966,167.839745,789.016473
2014,United States,USA,1581.710350,1138.630744,253.193074,79.866385,28.923690,43.693157,181.655282,797.165982
2015,United States,USA,1352.398197,1346.598808,243.988597,79.549452,39.032171,42.276556,190.718548,797.177877
2016,United States,USA,1239.148654,1391.114366,261.126026,78.586265,54.866492,37.959041,226.992562,805.693948
2017,United States,USA,1205.835275,1308.883659,293.838608,78.688434,77.276459,34.486074,254.302662,804.949635
2018,United States,USA,1145.962192,1482.189373,286.619450,77.868208,93.364598,38.198843,272.649789,807.084477
2019,United States,USA,964.957000,1598.303000,282.613000,72.980000,106.894000,31.772000,294.906000,809.409262
2020,United States,USA,773.805528,1629.236806,285.789644,72.984923,132.630484,28.947190,336.533331,789.918631

In [ ]:
#@title Kutilgan natija

             davlat  kod        komir  ...        neft    shamol        atom
yil                                    ...
1985  United States  USA  1507.664651  ...  107.744380  0.005820  403.884976
1986  United States  USA  1490.141346  ...  146.865448  0.004231  435.829540
1987  United States  USA  1573.958375  ...  127.411367  0.003577  479.231981
1988  United States  USA  1656.615886  ...  160.107055  0.000880  554.708470
1989  United States  USA  1711.442534  ...  176.729591  2.133377  557.215492

[5 rows x 10 columns]

### 5-VAZIFA. AQSh 2020-yilda jami qancha elektr energiyasi ishlab chiqqan?

In [7]:
# JAVOBNI SHU YERGA YOZING
dfus.tail()

,davlat,kod,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
yil,,,,,,,,,,
2016,United States,USA,1239.148654,1391.114366,261.126026,78.586265,54.866492,37.959041,226.992562,805.693948
2017,United States,USA,1205.835275,1308.883659,293.838608,78.688434,77.276459,34.486074,254.302662,804.949635
2018,United States,USA,1145.962192,1482.189373,286.619450,77.868208,93.364598,38.198843,272.649789,807.084477
2019,United States,USA,964.957000,1598.303000,282.613000,72.980000,106.894000,31.772000,294.906000,809.409262
2020,United States,USA,773.805528,1629.236806,285.789644,72.984923,132.630484,28.947190,336.533331,789.918631

In [8]:
dfus.loc[[2020],['komir','gaz','gidro','yangilanuvchi','quyosh','neft','shamol','atom']].sum(axis=1)

yil
2020    4049.846537
dtype: float64

In [9]:
dfus.iloc[35,2:10].sum()

4049.84653732

In [ ]:
#@title O'xshash natija (2018-yil uchun)

yil
2018    4203.93693
dtype: float64

### 6-VAZIFA. 2010-2020-yillarda AQSH turli manbaalardan o'rtacha qancha elektr toki olganini chiqaring. Natijani kichikdan kattaga qarab tartiblang.

In [10]:
# JAVOBNI SHU YERGA YOZING
dfus_2010_2020 = dfus.loc[[2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020]].mean(numeric_only=True)
dfus_2010_2020.sort_values()

neft               39.028512
quyosh             49.943642
yangilanuvchi      75.785131
shamol            207.386225
gidro             273.634436
atom              796.992746
gaz              1299.518378
komir            1358.154104
dtype: float64

In [11]:
# JAVOBNI SHU YERGA YOZING
dfus_2010_2020_2= dfus.iloc[25:36].mean(numeric_only=True)
dfus_2010_2020_2.sort_values()

neft               39.028512
quyosh             49.943642
yangilanuvchi      75.785131
shamol            207.386225
gidro             273.634436
atom              796.992746
gaz              1299.518378
komir            1358.154104
dtype: float64

In [ ]:
#@title O'xshash natija (1990-2000 yillar uchun)

quyosh              0.487222
shamol              3.472647
yangilanuvchi      65.175549
neft              114.206278
gidro             299.372340
gaz               500.845253
atom              684.580238
komir            1881.713514
dtype: float64

### 7-VAZIFA. AQSH gidro elektr stansiyalardan eng kam va eng ko'p elektr energiyasi olgan yillarni toping.

In [12]:
# JAVOBNI SHU YERGA YOZING
dfus['gidro'].idxmin()

2001

In [14]:
dfus['gidro'].idxmax()

1997

### 8-VAZIFA.
#### 8.1 Asl `df` dan 2019-yil ma'lumotlarini ajratib oling.
#### 8.2 Yangi df ga `df19` deb nom bering
#### 8.3 `df19` indeksini `davlat` ustuniga o'zgartiring hamda `davlat` va `yil` ustunlarini tashlab yuboring.
#### 8.4 `df19` dan `World` indeksini o'chirib tashlang

In [18]:
# JAVOBNI SHU YERGA YOZING
df19 = df[df.yil==2019]
df19

,davlat,kod,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
19,Afghanistan,AFG,2019,0.000000,0.152000,0.840000,0.000000,0.040000,0.000000,0.000000,0.000000
54,Africa,NaN,2019,253.555978,340.472820,132.734791,8.184247,19.377978,81.274240,17.508052,14.214193
74,Albania,ALB,2019,0.000000,0.000000,5.153940,0.000000,0.022000,0.000000,0.000000,0.000000
94,Algeria,DZA,2019,0.000000,73.615787,0.106440,0.000000,0.615000,0.000000,0.011000,0.000000
129,American Samoa,ASM,2019,0.000000,0.000000,0.000000,0.000000,0.000000,0.163000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
6144,Western Sahara,ESH,2019,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6179,World,OWID_WRL,2019,9081.622041,5943.112329,4261.241023,682.877296,704.023692,1089.307746,1416.947048,2720.674471
6200,Yemen,YEM,2019,0.000000,0.770710,0.000000,0.000000,0.500000,1.242770,0.000000,0.000000
6220,Zambia,ZMB,2019,1.998501,0.000000,13.772427,0.080073,0.000389,1.003232,0.000000,0.000000
6240,Zimbabwe,ZWE,2019,3.805433,0.000000,5.020000,0.206667,0.014000,0.000000,0.000000,0.000000

In [23]:
df19.set_index(df19.davlat, inplace=True)
df19

,davlat,kod,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
davlat,,,,,,,,,,,
Afghanistan,Afghanistan,AFG,2019,0.000000,0.152000,0.840000,0.000000,0.040000,0.000000,0.000000,0.000000
Africa,Africa,NaN,2019,253.555978,340.472820,132.734791,8.184247,19.377978,81.274240,17.508052,14.214193
Albania,Albania,ALB,2019,0.000000,0.000000,5.153940,0.000000,0.022000,0.000000,0.000000,0.000000
Algeria,Algeria,DZA,2019,0.000000,73.615787,0.106440,0.000000,0.615000,0.000000,0.011000,0.000000
American Samoa,American Samoa,ASM,2019,0.000000,0.000000,0.000000,0.000000,0.000000,0.163000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
Western Sahara,Western Sahara,ESH,2019,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
World,World,OWID_WRL,2019,9081.622041,5943.112329,4261.241023,682.877296,704.023692,1089.307746,1416.947048,2720.674471
Yemen,Yemen,YEM,2019,0.000000,0.770710,0.000000,0.000000,0.500000,1.242770,0.000000,0.000000
Zambia,Zambia,ZMB,2019,1.998501,0.000000,13.772427,0.080073,0.000389,1.003232,0.000000,0.000000
Zimbabwe,Zimbabwe,ZWE,2019,3.805433,0.000000,5.020000,0.206667,0.014000,0.000000,0.000000,0.000000

In [30]:
df19 = df19.drop(['davlat','yil'], axis=1)
df19

,kod,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
davlat,,,,,,,,,
Afghanistan,AFG,0.000000,0.152000,0.840000,0.000000,0.040000,0.000000,0.000000,0.000000
Africa,NaN,253.555978,340.472820,132.734791,8.184247,19.377978,81.274240,17.508052,14.214193
Albania,ALB,0.000000,0.000000,5.153940,0.000000,0.022000,0.000000,0.000000,0.000000
Algeria,DZA,0.000000,73.615787,0.106440,0.000000,0.615000,0.000000,0.011000,0.000000
American Samoa,ASM,0.000000,0.000000,0.000000,0.000000,0.000000,0.163000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
Western Sahara,ESH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
World,OWID_WRL,9081.622041,5943.112329,4261.241023,682.877296,704.023692,1089.307746,1416.947048,2720.674471
Yemen,YEM,0.000000,0.770710,0.000000,0.000000,0.500000,1.242770,0.000000,0.000000
Zambia,ZMB,1.998501,0.000000,13.772427,0.080073,0.000389,1.003232,0.000000,0.000000
Zimbabwe,ZWE,3.805433,0.000000,5.020000,0.206667,0.014000,0.000000,0.000000,0.000000

In [33]:
df19.drop(['World'])
df19

,kod,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
davlat,,,,,,,,,
Afghanistan,AFG,0.000000,0.152000,0.840000,0.000000,0.040000,0.000000,0.000000,0.000000
Africa,NaN,253.555978,340.472820,132.734791,8.184247,19.377978,81.274240,17.508052,14.214193
Albania,ALB,0.000000,0.000000,5.153940,0.000000,0.022000,0.000000,0.000000,0.000000
Algeria,DZA,0.000000,73.615787,0.106440,0.000000,0.615000,0.000000,0.011000,0.000000
American Samoa,ASM,0.000000,0.000000,0.000000,0.000000,0.000000,0.163000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
Western Africa,NaN,NaN,NaN,19.140564,0.369527,0.783808,NaN,0.189482,0.000000
Western Sahara,ESH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Yemen,YEM,0.000000,0.770710,0.000000,0.000000,0.500000,1.242770,0.000000,0.000000
Zambia,ZMB,1.998501,0.000000,13.772427,0.080073,0.000389,1.003232,0.000000,0.000000
Zimbabwe,ZWE,3.805433,0.000000,5.020000,0.206667,0.014000,0.000000,0.000000,0.000000

In [ ]:
#@title Kutilgan natija

                     kod       komir  ...     shamol       atom
davlat                                ...
Afghanistan          AFG    0.000000  ...   0.000000   0.000000
Africa               NaN  253.555978  ...  17.508052  14.214193
Albania              ALB    0.000000  ...   0.000000   0.000000
Algeria              DZA    0.000000  ...   0.011000   0.000000
American Samoa       ASM    0.000000  ...   0.000000   0.000000
Angola               AGO    0.000000  ...   0.000000   0.000000
Antarctica           ATA    0.000000  ...   0.000000   0.000000
Antigua and Barbuda  ATG    0.000000  ...   0.000000   0.000000
Argentina            ARG    0.740682  ...   4.997000   7.927000
Armenia              ARM    0.000000  ...   0.003000   2.029000

[10 rows x 9 columns]

#### 8.5 `df19` jadvali uchun umumlashtiruvchi statistikani chiqaring

In [34]:
# JAVOBNI SHU YERGA YOZING
df19.info()

<class 'pandas.core.frame.DataFrame'>
Index: 234 entries, Afghanistan to Zimbabwe
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   kod            210 non-null    object
 1   komir          225 non-null    float64
 2   gaz            225 non-null    float64
 3   gidro          234 non-null    float64
 4   yangilanuvchi  233 non-null    float64
 5   quyosh         234 non-null    float64
 6   neft           225 non-null    float64
 7   shamol         234 non-null    float64
 8   atom           234 non-null    float64
dtypes: float64(8), object(1)
memory usage: 26.4+ KB

In [35]:
df19.describe()

,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
count,225.000000,225.000000,234.000000,233.000000,234.000000,225.000000,234.000000,234.000000
mean,89.629863,63.570115,40.428494,7.378199,7.297140,10.575434,15.621916,30.370740
std,590.143698,224.662108,169.370944,29.920512,35.365822,36.389645,70.427073,136.481831
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.003195,0.042000,0.000000,0.000000
50%,0.000000,0.229147,0.991647,0.031000,0.040000,0.620333,0.008250,0.000000
75%,4.420929,20.635015,11.910820,1.314232,0.762633,3.872553,1.136484,0.000000
max,7376.390586,1975.752363,1783.656628,238.022873,393.921841,396.115102,514.259616,963.746826

### 9-VAZIFA. 2019-yilda har bir davlat jami qancha elektr energiya ishlab chiqarganini DF ko'rinishida chiqaring.
*ishora. `Series` obyektini `DF` ga o'tkazing

In [42]:
# JAVOBNI SHU YERGA YOZING
df19.sum(axis='columns', numeric_only=True).to_frame()

                         0
davlat
Afghanistan       1.032000
Africa          867.322298
Albania           5.175940
Algeria          74.348227
American Samoa    0.163000
...                    ...
Western Africa   20.483381
Western Sahara    0.000000
Yemen             2.513480
Zambia           16.854622
Zimbabwe          9.046100

[234 rows x 1 columns]

In [ ]:
#@title Kutilgan natija

                       max
davlat
Afghanistan       1.032000
Africa          867.322298
Albania           5.175940
Algeria          74.348227
American Samoa    0.163000
...                    ...
Western Africa   20.483381
Western Sahara    0.000000
Yemen             2.513480
Zambia           16.854622
Zimbabwe          9.046100

[234 rows x 1 columns]

### 10-VAZIFA.
#### 10.1. Asl DF dan 2000-2020-yillar, `France` uchun `atom`, `komir`, `gaz`, `quyosh` manbaalarini alohida `dffr` jadvaliga ko'chirib oling
#### 10.2. `dffr` jadvalini yil ustuni bo'yicha tartiblang

In [43]:
# JAVOBNI SHU YERGA YOZING
df

,davlat,kod,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
0,Afghanistan,AFG,2000,0.000000,0.155,0.312,0.000000,0.000,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.000000,0.094,0.498,0.000000,0.000,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.000000,0.132,0.555,0.000000,0.000,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.000000,0.309,0.630,0.000000,0.000,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.000000,0.329,0.565,0.000000,0.000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6236,Zimbabwe,ZWE,2015,4.311780,0.000,4.940,0.128000,0.008,0.0,0.0,0.0
6237,Zimbabwe,ZWE,2016,3.714880,0.000,2.955,0.147000,0.009,0.0,0.0,0.0
6238,Zimbabwe,ZWE,2017,3.218560,0.000,3.929,0.151000,0.011,0.0,0.0,0.0
6239,Zimbabwe,ZWE,2018,3.932020,0.000,5.000,0.187000,0.014,0.0,0.0,0.0
6240,Zimbabwe,ZWE,2019,3.805433,0.000,5.020,0.206667,0.014,0.0,0.0,0.0

In [54]:
dffr = df[df.davlat == 'France']
dffr.sample()

,davlat,kod,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
1947,France,FRA,2013,23.830994,18.393269,71.922175,6.040992,5.19359,11.01585,16.126736,423.684671

In [55]:
dffr[['yil','atom','komir','gaz','quyosh']]

       yil        atom      komir        gaz     quyosh
1934  2000  415.162000  27.004000  11.514000   0.005223
1935  2001  421.076000  20.478000  15.146000   0.006161
1936  2002  436.760000  23.658000  18.369000   0.007104
1937  2003  441.070000  26.260000  19.368000   0.007767
1938  2004  448.241000  24.372000  21.049000   0.008448
1939  2005  451.529000  27.515000  23.069000   0.010501
1940  2006  450.191000  22.889000  21.760000   0.012103
1941  2007  439.730000  24.446000  21.987000   0.017572
1942  2008  439.447000  23.063000  21.884000   0.041692
1943  2009  409.736000  21.667000  20.503000   0.173971
1944  2010  428.521000  23.359000  23.758000   0.620000
1945  2011  442.387763  17.807444  29.489144   2.333802
1946  2012  425.406017  21.449981  22.753254   4.427930
1947  2013  423.684671  23.830994  18.393269   5.193590
1948  2014  436.479009  11.242305  13.162876   6.391477
1949  2015  437.427808  11.873673  21.143153   7.753328
1950  2016  403.195482  10.344460  34.967086   8.659160
1951  2017  398.359129  12.818153  40.500366   9.584882
1952  2018  412.941812   8.412694  30.587768  10.568737
1953  2019  398.941812   4.412694  37.587768  12.568737
1954  2020  355.190804   4.275487  34.245560  13.190057
1955  1985  224.100000        NaN        NaN   0.000000
1956  1986  254.155000        NaN        NaN   0.000000
1957  1987  265.520000        NaN        NaN   0.000000
1958  1988  275.521000        NaN        NaN   0.000000
1959  1989  303.931000        NaN        NaN   0.000000
1960  1990  314.081000        NaN        NaN   0.000000
1961  1991  331.340000        NaN        NaN   0.000000
1962  1992  338.445000        NaN        NaN   0.001488
1963  1993  368.188000        NaN        NaN   0.001683
1964  1994  359.981000        NaN        NaN   0.001878
1965  1995  377.231000        NaN        NaN   0.002040
1966  1996  397.340000        NaN        NaN   0.002650
1967  1997  395.483000        NaN        NaN   0.003407
1968  1998  387.990000        NaN        NaN   0.004089
1969  1999  394.244000        NaN        NaN   0.004548

In [ ]:
#@title Kutilgan natija

       yil        atom      komir        gaz     quyosh
1934  2000  415.162000  27.004000  11.514000   0.005223
1935  2001  421.076000  20.478000  15.146000   0.006161
1936  2002  436.760000  23.658000  18.369000   0.007104
1937  2003  441.070000  26.260000  19.368000   0.007767
1938  2004  448.241000  24.372000  21.049000   0.008448
1939  2005  451.529000  27.515000  23.069000   0.010501
1940  2006  450.191000  22.889000  21.760000   0.012103
1941  2007  439.730000  24.446000  21.987000   0.017572
1942  2008  439.447000  23.063000  21.884000   0.041692
1943  2009  409.736000  21.667000  20.503000   0.173971
1944  2010  428.521000  23.359000  23.758000   0.620000
1945  2011  442.387763  17.807444  29.489144   2.333802
1946  2012  425.406017  21.449981  22.753254   4.427930
1947  2013  423.684671  23.830994  18.393269   5.193590
1948  2014  436.479009  11.242305  13.162876   6.391477
1949  2015  437.427808  11.873673  21.143153   7.753328
1950  2016  403.195482  10.344460  34.967086   8.659160
1951  2017  398.359129  12.818153  40.500366   9.584882
1952  2018  412.941812   8.412694  30.587768  10.568737
1953  2019  398.941812   4.412694  37.587768  12.568737
1954  2020  355.190804   4.275487  34.245560  13.190057

#### 10.3 `dffr`uchun Korrelyasiya jadvalini chiqaring.

In [58]:
# JAVOBNI SHU YERGA YOZING
dffr.corr()

<ipython-input-58-04ae4eca77f6>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  dffr.corr()

,yil,komir,gaz,gidro,yangilanuvchi,quyosh,neft,shamol,atom
yil,1.000000,-0.866541,0.732072,-0.300511,0.946415,0.767329,-0.041041,0.836125,0.721468
komir,-0.866541,1.000000,-0.665521,0.067225,-0.918671,-0.933234,0.059284,-0.921549,0.677929
gaz,0.732072,-0.665521,1.000000,-0.466301,0.777808,0.706133,0.130629,0.722891,-0.561700
gidro,-0.300511,0.067225,-0.466301,1.000000,-0.294591,-0.185064,-0.400671,-0.231316,-0.226157
yangilanuvchi,0.946415,-0.918671,0.777808,-0.294591,1.000000,0.920621,-0.010618,0.951225,0.488135
quyosh,0.767329,-0.933234,0.706133,-0.185064,0.920621,1.000000,0.065282,0.976499,0.178557
neft,-0.041041,0.059284,0.130629,-0.400671,-0.010618,0.065282,1.000000,-0.013924,0.183947
shamol,0.836125,-0.921549,0.722891,-0.231316,0.951225,0.976499,-0.013924,1.000000,0.250691
atom,0.721468,0.677929,-0.561700,-0.226157,0.488135,0.178557,0.183947,0.250691,1.000000